server:
  jwt:
    public-key: classpath:jwt.pub
    private-key: classpath:jwt.key
  servlet:
    context-path: '/api/v1'
  port: 8020
spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
  datasource:
    url: jdbc:mysql://resqpet.c6pack4a6in2.us-east-1.rds.amazonaws.com:3306/RESQPET
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Resqpet010203.
  jooq:
    sql-dialect: MYSQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
  sendgrid:
    api-key: "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"
aws:
  access-key: "AKIAQHVAIZA47NGU2D6X"
  secret-key: "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"
  s3:
    bucket: "resqpet.final.tds"
ia:
  api:
    url: "https://openrouter.ai/api/v1/chat/completions"
    key: "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"
app:
  emails:
    from: "resqpet.info@gmail.com"
    sender: "resQpet"
    base-path: "http://3.17.176.194:8020/api/v1"
    api-key: ${spring.sendgrid.api-key}
    templates:
      account-recover:
        subject: "Recuperación de Contraseña"
        template: "d-90ee41513e7e438aa04635175c9eb247"
        redirect-uri: "${app.emails.base-path}/auth/recover?token="
logging:
  level:
    org.hibernate: warn
    org.hibernate.orm.connections.pooling: warn
